language: python

sudo: false

deploy:
  provider: pypi user: {{ cookiecutter.travis_username }}
  password:
    secure:
  on:
    tags: true
    repo: {{ cookiecutter.github_handle }}/{{ cookiecutter.repo_name }}

python:
  - '3.8'

install:
- travis_retry pip install -r requirements-dev.txt
- travis_retry pip install -r requirements.txt

script:
- flake8 --ignore N802,N806 `find . -name \*.py | grep -v setup.py | grep -v version.py | grep -v __init__.py | grep -v /docs/`
- mkdir for_test
- cd for_test
- py.test --pyargs {{ cookiecutter.repo_name }} --cov-report term-missing --cov={{ cookiecutter.repo_name }}

after_success:
- coveralls
